### ISSUE TITLE
Import all issues from project

### ISSUE THREAD

**Issue by wojtek-fliposports** [somebox/jira-tracker-for-trello#11]
Is there any chance to add functionality to import all tasks/issues from given project ?

**Comment by somebox** [comment]
This could be added. But it was not really in the design of this app - the main goal was to keep JIRA and Trello in sync, not to import or migrate from JIRA to Trello. The problem I wanted to solve was to keep teams up-to-date when they use multiple tools.

However, you might be able to use the libraries to create a rake task to do this. If you want to submit a PR I am happy to review.
