### ISSUE TITLE
After run ./bin/trello-jira-bot - nothing

### ISSUE THREAD

**Issue by dimti** [somebox/jira-tracker-for-trello#6]
Hello

I set up all accounts and add comment to trello card

After run ./bin/trello-jira-bot - nothing

How to analyze that?

**Comment by dimti** [comment]
# Logfile created on 2015-08-30 21:22:44 +0300 by logger.rb/31641
    D, [2015-08-30T21:22:44.684248 #3742] DEBUG -- : Configuration loaded.
    I, [2015-08-30T21:22:44.684351 #3742]  INFO -- : Scanning Trello cards as @Jirabot5

**Comment by somebox** [comment]
Is it possible that there were no cards to process? the `@jirabot5` here must be members of some boards, and assigned to some cards. Then it will look for issues to track. 

If that was done and still no luck, you might try using `binding.pry` to check the API responses and make sure nothing has gone wrong there.

**Comment by dimti** [comment]
I solve problem with number 1. After add jirabot5 as member to the trello card - trellobot connected to the trello, but

Problem:
log:

    D, [2015-09-21T15:28:26.899645 #22216] DEBUG -- : Configuration loaded.
    I, [2015-09-21T15:28:26.899820 #22216]  INFO -- : Scanning Trello cards as @jirabot5
    I, [2015-09-21T15:28:30.079007 #22216]  INFO -- :  * Scanning Trello #3 (MEBLOG)

Stack trace:

root@dimti:/opt/jira-tracker-for-trello# ./bin/trello-jira-bot 
/var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/abstract_response.rb:48:in `return!': 403 Forbidden (RestClient::Forbidden)
        from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:495:in `process_result'
        from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:421:in `block in transmit'
        from /usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
        from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit'
        from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
        from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
        from /var/lib/gems/1.9.1/gems/rest-client-1.7.3/lib/restclient/resource.rb:51:in `get'
        from /opt/jira-tracker-for-trello/lib/jira/client.rb:15:in `get'
        from /opt/jira-tracker-for-trello/lib/jira/ticket.rb:72:in `exists?'
        from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:138:in `jira_ticket_exists?'
        from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:123:in `track_jira'
        from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:146:in `block in update_tracking_status'
        from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:143:in `each'
        from /opt/jira-tracker-for-trello/lib/bot/tracked_card.rb:143:in `update_tracking_status'
        from /opt/jira-tracker-for-trello/lib/bot/trello.rb:40:in `block in update'
        from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `each'
        from /opt/jira-tracker-for-trello/lib/bot/trello.rb:37:in `update'
        from ./bin/trello-jira-bot:29:in `<main>'
root@dimti:/opt/jira-tracker-for-trello# cat log/bot.log |less
root@dimti:/opt/jira-tracker-for-trello#

**Comment by dimti** [comment]
![_2015-09-21_15-32-49](https://cloud.githubusercontent.com/assets/582144/9991821/113655a0-6076-11e5-897b-76df98f9fd9e.png)

**Comment by dimti** [comment]
May be wrong auth data for jira rest api?

**Comment by somebox** [comment]
JIRA REST API permissions error is my guess. I'll close this since it's over a year old. But re-open if you wish.
