### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by felipefernandes** [somebox/jira-tracker-for-trello#7]
Hi,
I'm trying to install this tool but I'm having troubles with that.

I did the instructions described in README, but in the step that tells me to run the bundle command didn't work for me instead of install, I got a bunch of messages saying that I don't have access to read from remote repository (a pasted bash messages below). I'm not sure what is happening, could anyone help me solve it?

> macbookair@MacBook-Air-Felipe:~/Tools/jira-tracker$ bundle install
> Fetching gem metadata from http://rubygems.org/.......
> Fetching version metadata from http://rubygems.org/...
> Fetching dependency metadata from http://rubygems.org/..
> Fetching git@github.com:somebox/ruby-trello.git
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Retrying git clone 'git@github.com:somebox/ruby-trello.git' "/Users/macbookair/.bundler/cache/git/ruby-trello-<CODE>" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:somebox/ruby-trello.git' "/Users/macbookair/.bundler/cache/git/ruby-trello-<CODE>" --bare --no-hardlinks --quiet` in directory /Users/macbookair/Tools/jira-tracker has failed.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Git error: command `git clone 'git@github.com:somebox/ruby-trello.git'
> "/Users/macbookair/.bundler/cache/git/ruby-trello-<CODE>" --bare --no-hardlinks --quiet` in directory
> /Users/macbookair/Tools/jira-tracker has failed.

Thanks,
Felipe

**Comment by somebox** [comment]
Hello, I'm not sure why you got a permission error, my fork of that gem is public. However, I have updated this project to use the official repo for ruby-trello, so I'll close this issue.
